name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23liO8Uj4eRUjiYn5Q"
GITHUB_OWNER = "358120997"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://dh.guojubb.top/api/auth"
NEXT_PUBLIC_API_URL="https://dh.guojubb.top"

